name: Rust Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-freebsd

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain with targets
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install linker dependencies (Linux)
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Install linker dependencies (FreeBSD)
        if: matrix.target == 'x86_64-unknown-freebsd'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm lld

      - name: Configure FreeBSD linker
        if: matrix.target == 'x86_64-unknown-freebsd'
        run: |
          mkdir -p ~/.cargo
          echo '[target.x86_64-unknown-freebsd]' >> ~/.cargo/config.toml
          echo 'linker = "clang"' >> ~/.cargo/config.toml

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-binary
          path: target/${{ matrix.target }}/release/tiny_twilio_stripe
