name: Rust Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-freebsd

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain and targets
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install build-essential and linker symlink for Linux
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          sudo ln -sf $(which gcc) /usr/bin/x86_64-unknown-linux-gnu-gcc

      - name: Install linker dependencies for FreeBSD
        if: matrix.target == 'x86_64-unknown-freebsd'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm lld

      - name: Build project
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-binary
          path: target/${{ matrix.target }}/release/tiny_twilio_stripe
