name: Rust Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-freebsd

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain and targets
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install dependencies & symlink for Linux target
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          sudo ln -sf $(which gcc) /usr/bin/x86_64-unknown-linux-gnu-gcc

      - name: Install dependencies & configure linker for FreeBSD target
        if: matrix.target == 'x86_64-unknown-freebsd'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm lld
          rustup target add x86_64-unknown-freebsd
          # Explicitly FORCE Cargo environment variables to correct linker/ar
          echo "CARGO_TARGET_X86_64_UNKNOWN_FREEBSD_LINKER=clang" >> "$GITHUB_ENV"
          echo "CARGO_TARGET_X86_64_UNKNOWN_FREEBSD_AR=llvm-ar" >> "$GITHUB_ENV"

      - name: Build project
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-binary
          path: target/${{ matrix.target }}/release/tiny_twilio_stripe
