name: Rust Cross-Platform Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Symlink gcc to expected linker name
        run: |
          which gcc
          sudo ln -s "$(which gcc)" /usr/bin/x86_64-unknown-linux-gnu-gcc

      - name: Build Linux binary (native)
        run: cargo build --release --target x86_64-unknown-linux-gnu
        
  build-freebsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Install FreeBSD GCC toolchain
        run: sudo apt-get update && sudo apt-get install -y gcc-x86-64-freebsd

      - name: Configure FreeBSD linker
        run: |
          sudo ln -s "$(which x86_64-freebsd-gcc)" /usr/bin/x86_64-unknown-freebsd-gcc
          sudo ln -s "$(which x86_64-freebsd-gcc)" /usr/bin/x86_64-unknown-linux-gnu-gcc

      - name: Build FreeBSD binary (using cross)
        run: cross build --release --target x86_64-unknown-freebsd
