name: Rust Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-freebsd

    runs-on: ubuntu-latest

    container:
      image: rustembedded/cross:${{ matrix.target }}

    steps:
      - uses: actions/checkout@v4

      - name: Build release binary
        run: cargo build --release --target ${{ matrix.target }}
