name: Rust CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-freebsd

    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc clang llvm

    - name: Install Rust target
      run: rustup target add ${{ matrix.target }}

    - name: Install linker for FreeBSD
      if: matrix.target == 'x86_64-unknown-freebsd'
      run: |
        sudo apt-get install -y clang lld
        mkdir -p ~/.cargo
        echo '[target.x86_64-unknown-freebsd]' >> ~/.cargo/config.toml
        echo 'linker = "clang"' >> ~/.cargo/config.toml

    - name: Build project
      run: cargo build --target ${{ matrix.target }} --verbose
