name: Rust Cross-Compilation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Install Rust with required targets
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: |
          x86_64-unknown-linux-gnu
          x86_64-unknown-freebsd

    # Install required system packages (cross-compilers)
    - name: Install build-essential and cross-compilation tools
      run: |
        sudo apt update
        sudo apt install -y build-essential gcc clang llvm pkg-config
        sudo apt install -y gcc-x86-64-linux-gnu
        sudo apt install -y gcc-multilib

    # For FreeBSD, install cross linker via cross
    - name: Install cross
      uses: taiki-e/install-action@cross

    # Build for Linux (native)
    - name: Build (Linux x86_64)
      run: cargo build --verbose --target=x86_64-unknown-linux-gnu

    # Cross-build for FreeBSD (cross)
    - name: Cross-build (FreeBSD x86_64)
      run: cross build --verbose --target=x86_64-unknown-freebsd
